# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on: push

env:
  GITHUBRUNID: ${{ github.run_id }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: demo
    steps:
    - uses: actions/checkout@v2
    - name: Install Java
      id: sdkman
      run: |
        curl -s "https://get.sdkman.io" | bash
        source "/home/runner/.sdkman/bin/sdkman-init.sh"
        sdk install java 17.0.3.6.1-amzn
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        source "/home/runner/.sdkman/bin/sdkman-init.sh"
        sdk use java 17.0.3.6.1-amzn
        ./gradlew localDistro
